CREATE TABLE psn_nicks
(
  idpsn_nicks INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  pn_chat_id VARCHAR(100),
  pn_psn_nick VARCHAR(100)
);

CREATE TABLE settings (
  ST_KEY VARCHAR(100) NOT NULL COMMENT '',
  ST_VALUE VARCHAR(200) NULL COMMENT '',
  PRIMARY KEY (ST_KEY)  COMMENT ''
);

INSERT INTO settings (ST_KEY, ST_VALUE) VALUES ('DB_FILE_NAME', 'temp');
INSERT INTO settings (ST_KEY, ST_VALUE) VALUES ('DB_VERSION', '0');
